services:
  - type: web
    name: evaluacion-certificacion
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8

      # Flask
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py

      # TZ local
      - key: DEFAULT_TZ
        value: America/Mexico_City

      # Seguridad
      - key: SECRET_KEY
        generateValue: true

      # Supabase (usa el Transaction Pooler; típico puerto 6543)
      - key: DATABASE_URL
        value: postgresql://postgres.yqitswifdjjzitzobtyx:Saltillo07@aws-1-us-east-2.pooler.supabase.com:6543/postgres


    healthCheckPath: /api/evaluaciones/diag
    autoDeploy: true
